version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PASSWORD=settapass
      - TOKEN=b7c5b34f6f03cfa52a4780c64af1c93c
      - OURIP=24
      - NTEAM=44
